version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

  streamlit:
    build:
      context: .
    command: streamlit run app.py
    depends_on:
      - mysql
    ports:
      - "8501:8501"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
